---
title: "Exploring R Package Downloads from CRAN"
author: "Gaurav Sharma"
date: "29/08/2020"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      dpi = 180,
                      fig.width = 8,
                      fig.height = 5)

library(tidyverse)
library(scales)
library(lubridate)
library(countrycode)
theme_set(theme_light())
```

```{r}
ttfile <- tidytuesdayR::tt_load("2018-10-30")
r_downloads_year_raw <- ttfile$r_downloads_year
#r_downloads <- ttfile$`r-downloads`

r_downloads_year <- r_downloads_year_raw %>%
  select(-X1) %>%
  mutate(country = countrycode(country, "iso2c", "country.name"))
  
```

### Downloads over time

### Daily downloads
```{r R downloads}
r_downloads_year %>%
    count(date) %>% 
    ggplot(aes(date, n)) +
    geom_line() +
    expand_limits(y = 0) +
    labs(title = "# of R downloads per day")
```

### Lets have a look at weekly trend
```{r}
r_downloads_year %>% 
    count(date) %>% 
    mutate(weekday = wday(date,label = T)) %>% 
    group_by(weekday) %>%
    summarise(Avg = mean(n)) %>% 
    ggplot(aes(weekday, Avg)) +
    geom_line(group = 1, size = 1, color = "blue", alpha = 0.7) +
    expand_limits(y = 0) +
    labs(title = "# of R downloads on weekdays")
```

### Weekly downloads
```{r}
r_downloads_year %>% 
    mutate(week = floor_date(date, "week")) %>% 
    count(week) %>% 
    filter(week > min(week),
           week < max(week)) %>% 
    ggplot(aes(week, n)) +
    geom_line(group = 1, size = 1.5, color = "pink") +
    expand_limits(y = 0) +
    labs(title = "# of R downloads over weeks")
```

### Downloads per country
```{r}
r_downloads_year %>% 
    filter(!is.na(country)) %>% 
    count(country, sort = T) %>% 
    head(16) %>% 
    mutate(n = n/sum(n),
           country = fct_reorder(country,n)) %>% 
    ggplot(aes(country,n)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = percent_format()) +
    labs(title = "Which countries install R the most",
         subtitle = "Over 47% of the R downloads happen from United States",
         x = "",
         y = "% downloads")
```

### Lets see how Rs' different versions downloads has happened over time
```{r}
r_downloads_year %>%
    mutate(version = fct_lump(version, 10)) %>% 
    count(date, version) %>% 
    ggplot(aes(date,n, color = version)) +
        geom_line(size =1)
```

```{r}
r_downloads_year %>%
  mutate(version = fct_lump(version, 10)) %>%
  count(date, version) %>%
  ggplot(aes(date, n, color = version)) +
  geom_line(size = 1) +
  facet_wrap( ~ version)

```

### What time of day are people installing R the most
```{r}
r_downloads_year %>% 
  count(hour = hour(time)) %>% 
  ggplot(aes(hour, n)) +
    geom_line(size = 1.5, color = "orange", alpha = 0.6) +
  expand_limits(y = 0)
```

```{r}
r_downloads_year %>% 
  filter(!is.na(country)) %>% 
  mutate(country = fct_lump(country, 8)) %>% 
  count(country,
        hour = hour(time)) %>% 
  ggplot(aes(hour, n)) +
    geom_line(size = 1, color = "violet") +
  expand_limits(y = 0) +
  facet_wrap(~country, scales = "free_y")
```

```{r}
r_downloads_year %>%
  filter(!is.na(country)) %>%
  mutate(country = fct_lump(country, 8)) %>%
  count(country, date, hour = hour(time)) %>%
  group_by(country, hour) %>%
  summarise(avg_hr = mean(n)) %>%
  ggplot(aes(hour, avg_hr)) +
  geom_line(size = 1, color = "red", alpha = 0.7) +
  expand_limits(y = 0) +
  facet_wrap( ~ country, scales = "free_y")
```

### What operating systems do people use
```{r}
r_downloads_year %>% 
  count(os, sort = T) %>% 
  filter(!is.na(os)) %>% 
  mutate(n = n/sum(n),
         os = fct_reorder(os,n)) %>% 
  ggplot(aes(os, n)) +
  geom_col() +
  coord_flip()
```

```{r}
r_downloads_year %>% 
  filter(!is.na(os),
         !is.na(country)) %>% 
  mutate(country = fct_lump(country,8)) %>% 
  count(country, os, week = floor_date(date, "week")) %>% 
  filter(week > min(week)) %>% 
  ggplot(aes(week, n, color = os)) +
  geom_line(size =1) +
  expand_limits(y = 0) +
  facet_wrap(~country, scales = "free_y")
```

```{r}
r_downloads_year %>% 
#  filter(!is.na(country)) %>% 
  mutate(country = fct_lump(country,8)) %>% 
  count(country, week = floor_date(date, "week")) %>% 
  filter(week > min(week)) %>% 
  ggplot(aes(week, n, color = country)) +
  geom_line(size =1) +
  expand_limits(y = 0)
```

```{r}

```














